# Generated by Django 5.1.4 on 2024-12-13 13:52

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('meta_name', models.CharField(blank=True, max_length=255)),
                ('meta_keyword', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('url', models.SlugField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('meta_name', models.CharField(blank=True, max_length=255)),
                ('meta_keyword', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('url', models.SlugField()),
                ('parent_id', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('sapo', models.CharField(max_length=255)),
                ('avatar', models.ImageField(blank=True, upload_to='avatar')),
                ('news_type', models.CharField(choices=[('normal', 'Normal'), ('video', 'Video'), ('image', 'Image')], max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('edited_by', models.CharField(blank=True, max_length=200)),
                ('is_on_home', models.BooleanField(default=False)),
                ('is_focus', models.BooleanField(default=False)),
                ('is_pr', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TagNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.news')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tag')),
            ],
        ),
        migrations.CreateModel(
            name='NewsInZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.news')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zone')),
            ],
        ),
    ]
