# Generated by Django 5.1.4 on 2024-12-18 13:43

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_authorprofile_avatar_authorprofile_full_name_and_more'),
        ('core', '0002_alter_news_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('meta_name', models.CharField(blank=True, max_length=255)),
                ('meta_keyword', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('url', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('sapo', models.CharField(max_length=255)),
                ('avatar', models.ImageField(blank=True, upload_to='avatar_blog')),
                ('status', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('edited_by', models.CharField(blank=True, max_length=200)),
                ('is_on_home', models.BooleanField(default=False)),
                ('is_focus', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.author')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='NewsInCate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.blog')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
    ]
