services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: django_app
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "ReporterDEV.ReporterDEV.wsgi:application"]
    volumes:
      - .:/ReporterDEV
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env  # Load biến môi trường từ file .env

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  mysql_data:

